### ISSUE TITLE
[Bug] seem to be interpreter bug

### ISSUE THREAD

**Issue by duylam** [buunguyen/bike#20]
var ticks = 9000000;
var day = 10 , month = 10, year = 1000;
try {
    var net_dt = System.DateTime( 9000000 );
    println( 'done 1' );
    var net_dt2 = System.DateTime( year, month, day ); # run time error, expect no error
    println( 'done 2' );
} rescue e {
    println( 'error' );
    println( e.cause );
}
# The error log

done 1
error
System.InvalidCastException: Specified cast is not valid.
   at Bike.Interpreter.Interpreter.TypeCompatibilityRule.Convert(Type targetType, Object owner, Object& value)
   at Bike.Interpreter.Interpreter.TryConvert(Type targetType, Object owner, Object& value)
   at Fasterflect.TryInvokeWithValuesExtensions.TryCall(ParameterConverter converter, IEnumerable`1 methodBases, Object obj, Object[] parameterValues)
   at Fasterflect.TryInvokeWithValuesExtensions.TryCreateInstanceWithValues(Type type, ParameterConverter converter, BindingFlags flags, Object[] parameterValues)
   at Bike.Interpreter.Interpreter.<>c__DisplayClass11.<CreateInstance>b__10(Object[] innerArgs)
   at Bike.Interpreter.Interpreter.PerformInvocation(Object target, String funcName, Object[] args, Func`2[] invokers)
   at Bike.Interpreter.Interpreter.CreateInstance(Type type, Object[] args)
   at Bike.Interpreter.Interpreter.AccessOneByOne(Object currentTarget, Object previousTarget, List`1 suffixes)
   at Bike.Interpreter.Interpreter.Call(CallExpression node, IEnumerable`1 suffixes)
   at Bike.Interpreter.Interpreter.Walk(CallExpression node)
#    at Bike.Ast.CallExpression.Accept(IWalker walker)

**Comment by buunguyen** [comment]
Fixed in latest interpreter

**Comment by duylam** [comment]
Is the installer updated with latest intepreter ?

I run the rar file and re-install Bike (without uninstalling) but the bug is still there

**Comment by buunguyen** [comment]
Not updated the installer yet.  But I emailed you the updated interpreter already.

**Comment by duylam** [comment]
The DateTime constructor works now. But I get error when accessing Day property

Check below code

var ticks = 9000000;
var day = 10 , month = 10, year = 1000;
try {
    var net_dt = System.DateTime( 9000000 );
    println( 'done 1' );
    var net_dt2 = System.DateTime( year, month, day ); # run time error
    println( 'done 2' );
    println( 'Day=' + net_dt2.Day); // Error here
    println( 'Day+1=' + net_dt2.AddDays(1).Day);
} rescue e {
    println( 'error' );
    println( e.cause );
}

The output :

done 1
done 2
error
System.InvalidCastException: Unable to cast object of type 'System.DateTime' to type 'Fasterflect.Emitter.ValueTypeHolder'.
   at getter(Object )
   at Fasterflect.PropertyInfoExtensions.Get(PropertyInfo propInfo, Object obj)
   at Bike.Interpreter.Interpreter.TryGetInstanceProperty(Object target, String propName, Boolean& exist)
   at Bike.Interpreter.Interpreter.GetInstanceProperty(Object target, String propName)
   at Bike.Interpreter.Interpreter.AccessOneByOne(Object currentTarget, Object previousTarget, List`1 suffixes)
   at Bike.Interpreter.Interpreter.Member(MemberExpression node, IEnumerable`1 suffixes)
   at Bike.Interpreter.Interpreter.Walk(MemberExpression node)
   at Bike.Ast.MemberExpression.Accept(IWalker walker)
